---
cloud_controller_uri: http://api.cloud-controller
mbus: nats://nats:time4fun@9.115.210.219:4222
port: 8072
data_file: /home/vcap/admin_ui_0901/data/data.json
stats_file: /home/vcap/admin_ui_0901/data/stats.json
log_file: /home/vcap/admin_ui_0901/log/admin_ui.log
ui_credentials:
  username: user
  password: passw0rd
ui_admin_credentials:
  username: admin
  password: passw0rd
dea_retries: 10
nats_discovery_timeout: 10
component_connection_retries: 2
sender_email:
  server: 10.10.10.10
  account: system@email.com
receiver_emails: ["changlongwu@cn.ibm.com"]
monitored_components:
  - NATS
  - CloudController
  - DEA
  - HealthManager
  - Router
  - -Provisioner
  - ALL
cache_refresh_interval: 10
tasks_refresh_interval: 5000
stats_refresh_time: 300
stats_retry_interval: 300
stats_retries: 5
log_file_page_size: 51200
log_files:
  - /var/vcap/store/log/*.log
