#source "http://rubygems.org"
source "http://ruby.taobao.org"

gem "rake"

gem "vcap_common"
gem "steno", "~> 1.1.0"

gem "eventmachine", "~> 1.0.0"
gem "yajl-ruby"
gem "rest-client"
gem "em-http-request"
gem "cf-message-bus"

gem 'data_mapper'
gem 'dm-postgres-adapter'

group :test do
  gem "sinatra"
  gem "httparty"
  gem "rspec"
  gem "timecop"
end
